video_processing_response_schema = {
    "type": "object",
    "properties": {
        "speech_tone": {"type": "string"},
        "face_mimic": {"type": "string"},
        "gesticulation": {"type": "string"},
        "emotions": {"type": "string"},
        "hate_speech": {"type": "string"},
        "speech_quality": {"type": "string"},
        "discrepancies": {"type": "string"},
        "noises": {"type": "string"},
        "speech_pace": {"type": "string"},
        "own_suggestions": {"type": "string"},
    },
    "required": [
        "speech_tone",
        "face_mimic",
        "gesticulation",
        "emotions",
        "hate_speech",
        "speech_quality",
        "discrepancies",
        "noises",
        "speech_pace",
        "own_suggestions",
    ],
}
